# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Null Space
email: sp301415@gmail.com
author:
  name: sp301415
  url: https://sp301415.com
description: "sp301415의 블로그"
baseurl: ""
url: "https://blog.sp301415.com"
date_format: "%Y-%m-%d"
locale: ko_KR
timezone: Asia/Seoul

# Build settings
permalink: /:title/
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  input: GFMInlineMath
  syntax_highlighter: rouge
  math_engine: sskatex
  math_engine_opts:
    katex_js: _scripts/katex.js
    js_run: MiniRacer
  footnote_backlink: "&#8617;&#xfe0e;"

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _headers

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - cache/
  - gems/
  - ruby/
  - requirements.txt

# Default values
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/opengraph/default.png
      sitemap: false
      robots: noindex
  -
    scope:
      path:
      type: posts
    values:
      layout: post
      robots: all
      sitemap: true
  -
    scope:
      path: "index.html"
    values:
      robots: all
      sitemap: true
