name: Build Jekyll Blog

on:
  push:
    branches:
      - main

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
        
    - name: Generate OpenGraph Images
      run: |
        cd $GITHUB_WORKSPACE/_plugins
        pip install pillow
        python generate-ogimg.py
    - name: "Build Cache"
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: "Build & Push Jekyll Blog"
      uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.JEKYLL_TOKEN }}
        target_branch: 'gh-pages'